### ISSUE TITLE
fsck failing for XFS Arch install

### ISSUE THREAD

**Issue by alosarjos** [anatol/booster#128]
Hi there!

Before anyhing, thanks a lot for this project, is day and night compared to mkinitramfs.

I have a system with a / and /home as XFS partitions and the /boot as Fat32. The / and /home are under a LVM PV.

If I add the fsck files to the config file, booster says that fsck failed with code 0x8 for root (Which is at /dev/archlinux/root).

I have passed xfs_repair to both / and /home from a live usb and still is failing. Am I doing soemthing wrong?

Mi config file:

```yaml
modules: xfs
modules_force_load: amdgpu
extra_files: fsck,fsck.xfs,xfs_repair,fsck.fat
enable_lvm: true
```
