### ISSUE TITLE
[Help/Question] Network Bound Disk Unlocking (Clevis) using Tang on Alpine Linux

### ISSUE THREAD

**Issue by gb-123-git** [anatol/booster#262]
Hello,

I am having trouble creating booting **_Alpine Linux(v 3.19)_** with boot image created by booster, so I wanted to check if the configuration is correct before filing any bug report.
The intent of his test is to generate boot image using booster to unlock LUKS boot partition using clevis and tang.

I have installed the following apks : 
1. clevis
2. booster

My configurations:

_**/etc/booster.yaml**_
```
# Reference Manual @ https://man.archlinux.org/man/booster.1
network:
  interfaces: eth0
  dhcp: on
universal: false
enable_lvm: true

# default to gzip since that's what mkinitfs uses
compression: gzip

# timeout if mounting of fs fails within given timespan
mount_timeout: 0m60s

# uncomment to enable emergency shell on error/timeout
extra_files: fsck,fsck.ext4

```

**_/etc/update-extlinux.d/booster_** 
```
LABEL booster
        MENU LABEL Linux lts (booster)
        LINUX vmlinuz-lts
        INITRD booster-lts
        APPEND root=/dev/xvda2 rootfstype=ext4 ip=dhcp rd.luks.uuid=5xxxxx-7xxx-4xxx-8xxx-040decxxxxxx rd.neednet=1

```
Note: 
/dev/xvda2 maps to /dev/mapper/vg0-lv_root once unlocked and booted.

Results : 

The image created fails to boot as it fails to unlock using clevis and asks for a password.
Once the password is provided, it fails to boot as it fails to find the root drive.
I also noticed that uuid of the root that it is trying to find is different from the one provided.

Anything wrong in my configuration ?

**Comment by gb-123-git** [comment]
@anatol @nmeum @firasuke 
Any help would be appreciated. I have gone through everything online but somehow unable to get this working. I really want to switch over to booster.
Thanks a lot.

**Comment by anatol** [comment]
Hi @gb-123-git ,

Let's try to debug. Here are a few things you can try:
- use different way to reference your root device, something like `UUID=xxx`. Maybe name `xvda2` was not correctly mapped.
- Enable universal mode
- Enable debugging to print more information about the boot sequence. The post the debug logs to us.

**Comment by gb-123-git** [comment]
@anatol 
Thanks for the guidance.

Here is my setup:
```
This is a VM:
OS : Alpine Linux 3.19
blkid Output (when default boot image is used):

/dev/xvda1: UUID="ex-x-x-x-x" BLOCK_SIZE="1024" TYPE="ext4" PARTUUID="x-01"
/dev/xvda2: UUID="5x-7x-4x-8x-0x" TYPE="crypto_LUKS" PARTUUID="x-02"
/dev/mapper/vg0-lv_swap: UUID="3x-ax-4x-8x-8x" TYPE="swap"
/dev/mapper/vg0-lv_root: UUID="6x-ex-4x-bx-fx" BLOCK_SIZE="4096" TYPE="ext4"
/dev/mapper/root: UUID="Px-Gx-nx-zx-0x-3x-Qx" TYPE="LVM2_member"
```

Which `root=UUID=$UUID` should I be using from the above?

Updated **/etc/update-extlinux.d/booster**
```
LABEL booster
	MENU LABEL Linux lts (booster)
        LINUX vmlinuz-lts
        INITRD booster-lts
        APPEND rd.luks.uuid=5x-7x-4x-8x-0x root=UUID=6x-ex-4x-bx-fx rootfstype=ext4 booster.log=debug,console

```

My new **/etc/booster.yaml**
```
# Reference Manual @ https://man.archlinux.org/man/booster.1 
network:
  dhcp: on
universal: true
append_all_modaliases: true
enable_lvm: true
compression: gzip
mount_timeout: 0m15s
extra_files: busybox,nano,fsck,fsck.ext4
```

Result : 
I get something like 
`booster:  /dev/dm-2 /dev/mapper/vg0-lv_root : file exists`
and then
`sh: can't access tty; job control turned off`

So I am unable to run dmesg command and/ or post logs.

This is after I manually enter the password for unlock. Booster does not seem to network unlock.
I manually entered the password to see if I can get to any console so that I can further debug.

The messages on screen come so fast that I cant capture them.

**Comment by gb-123-git** [comment]
@anatol 
Hi ! Its been a year since I have been relentlessly trying to get this to work on an Alpine VM 
Would really appreciate if you can help! I also want to write a tutorial on this once I am able to install and run this.

I have managed to get dmesg & lsmod commands to work on busybox and but somehow I am not getting the network.
Would is be possible if you can have a look at my new configuration files ?

booster.yaml
```
# Network configuration
network:
  #Can also add additional values including MAC IDs eg : "enp0s31f2,2e:1d:61:30:a3:63"
  #If no interfaces is present, then all interfaces are activated.
  interfaces: eth0
  dhcp: on
  dns_servers: 8.8.8.8,8.8.4.4

# Enable universal mode for automatic LUKS detection
universal: true

#modules: -*,hid_apple,kernel/sound/usb/,kernel/fs/btrfs/btrfs.ko,kernel/lib/crc4.ko.xz
#modules: hid_generic
modules: '*'

modules_force_load: e1000e,virtio_net,crypto,crypto_user,encrypted_keys

append_all_modaliases: true

# default to gzip since that's what mkinitfs uses
compression: gzip

# timeout if mounting of fs fails within given timespan
mount_timeout: 0m30s

#* Extra files to include in initramfs
# extra_files is a comma-separated list of extra files to add to the image. If an item starts with slash ("/") then it is considered an absolute path. Otherwise it is a path relative to /usr/bin. If the item is a directory then its content is added recursively. There are a few special cases:
# adding busybox to the image enables an emergency shell in case of a panic during the boot process.
# adding fsck enables boot time filesystem check. It also requires filesystem specific binary called fsck.$rootfstype to be added to the image. Filesystems are corrected automatically and if it fails then boot stops and it is responsibility of the user to fix the root filesystem.
extra_files: busybox,fsck,fsck.ext4,curl,clevis,clevis-decrypt,clevis-decrypt-tang,clevis-decrypt-sss,clevis-luks-unlock,jose,nano,less,tftp-now-linux-amd64,/etc/ssl/certs/,/etc/resolv.conf,/bin/dmesg,/bin/cat,/bin/grep,/bin/ping,/sbin/lsmod,/sbin/blkid

#vconsole: true

enable_lvm: true
```
