### ISSUE TITLE
lvm above raid does not recognized

### ISSUE THREAD

**Issue by alexminder** [anatol/booster#271]
I have block device structure:

```
sda
├─sda1
│ └─md127
│   └─vg_encl_rd1-lv_encl_rd1
└─sda2
  └─vg_encl_rd0-lv_encl_rd0
sdb
├─sdb1
│ └─md127
│   └─vg_encl_rd1-lv_encl_rd1
└─sdb2
  └─vg_encl_rd0-lv_encl_rd0
  ```
*`booster.yaml`*:
```yml
universal: false
modules: sg,scsi_mod,usb_storage,uas,xhci_hcd,xhci_pci,raid0,raid1,raid10,dm_thin_pool,dm_cache_smq,amd_rng,efivarfs,xfs
modules_force_load: sg,scsi_mod,usb_storage,uas,xhci_hcd,xhci_pci,raid0,raid1,raid10,dm_thin_pool,dm_cache_smq,amd_rng,efivarfs,xfs
compression: zstd
strip: false
enable_lvm: true
enable_mdraid: true
```
booster creates md device and vg_encl_rd0-lv_encl_rd0, but not vg_encl_rd1-lv_encl_rd1.
From debug log it looks like lvm scan happens before creating md device. When md device created udev action appears but no further steps by booster happens.
