### ISSUE TITLE
Handle configurations for multiple images/kernels

### ISSUE THREAD

**Issue by anatol** [anatol/booster#30]
Some users have multiple kernels installed. Booster handles them by generating images for all the kernels. It uses `/etc/booster.yaml` config for all the images. But there are cases when one would want to have different config options for different kernels. For example `linux-lts` based on Linux 5.4 does not support zstd compression and needs to use something like `gzip` while newer kernel could use zstd compression.

Add possibility to overwrite variant-specific config options. One proposal is to have an additional configuration section something like

```yaml
compression: zstd # default value
...
variant:
  linux-lts:
    compression: gzip # overwrites the option for this particular variant
    modules: ...
```
